language: python
matrix:
  include:
  - os: linux
    sudo: false
    dist: trusty
    python: '2.7'
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=2.7
before_install:
- wget https://raw.githubusercontent.com/Horta/travis-miniconda/master/install.sh
  -O install.sh
- chmod +x install.sh
- travis_retry bash -x ./install.sh
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
before_script:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- pwd
- find .
- python setup.py test
script:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import fscLVM; print(fscLVM.__version__)"
- popd
notifications:
  email: false
branches:
  only:
  - master
deploy:
  provider: pypi
  user: flophys
  on:
    distributions: sdist bdist_wheel
    repo: PMBio/f-scLVM