name: tmp
channels:
  listitems:
  - bioconda
  - defaults
dependencies:
- _license=1.1=py27_1
- _nb_ext_conf=0.3.0=py27_0
- anaconda=4.2.0=np111py27_0
- anaconda-clean=1.0.0=py27_0
- anaconda-navigator=1.3.1=py27_0
- appnope=0.1.0=py27_0
- appscript=1.0.1=py27_0
- argcomplete=1.0.0=py27_1
- astroid=1.4.7=py27_0
- astropy=1.2.1=np111py27_0
- backports=1.0=py27_0
- beautifulsoup4=4.5.1=py27_0
- bioconda::click=6.6=py27_0
- bioconda::jmespath=0.9.0=py27_0
- bitarray=0.8.1=py27_0
- blaze=0.10.1=py27_0
- bokeh=0.12.2=py27_0
- boto=2.42.0=py27_0
- boto3=1.4.0=py27_0
- cdecimal=2.3=py27_2
- cffi=1.7.0=py27_0
- chest=0.2.3=py27_0
- clyent=1.2.2=py27_0
- configobj=5.0.6=py27_0
- cryptography=1.5=py27_0
- curl=7.49.0=1
- datashape=0.5.2=py27_0
- docutils=0.12=py27_2
- dynd-python=0.7.2=py27_0
- et_xmlfile=1.0.1=py27_0
- fastcache=1.0.2=py27_1
- flask-cors=2.1.2=py27_0
- freetype=2.5.5=1
- get_terminal_size=1.0.0=py27_0
- gevent=1.1.2=py27_0
- greenlet=0.4.10=py27_0
- grin=1.2.1=py27_3
- h5py=2.6.0=np111py27_2
- hdf5=1.8.17=1
- heapdict=1.0.0=py27_1
- icu=54.1=0
- jbig=2.1=0
- jdcal=1.2=py27_1
- jedi=0.9.0=py27_1
- jupyter=1.0.0=py27_3
- lazy-object-proxy=1.2.1=py27_0
- libdynd=0.7.2=0
- libpng=1.6.22=0
- libtiff=4.0.6=2
- libxml2=2.9.2=0
- libxslt=1.1.28=2
- llvmlite=0.13.0=py27_0
- markupsafe=0.23=py27_2
- matplotlib=1.5.3=np111py27_0
- mistune=0.7.3=py27_1
- mkl=11.3.3=0
- mkl-service=1.1.2=py27_2
- mpmath=0.19=py27_1
- numba=0.28.1=np111py27_0
- numpy=1.11.1=py27_0
- odo=0.5.0=py27_1
- openpyxl=2.3.2=py27_0
- openssl=1.0.2j=0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.4=py27_0
- pillow=3.3.1=py27_0
- pkginfo=1.3.2=py27_0
- ply=3.9=py27_0
- psutil=4.3.1=py27_0
- py=1.4.31=py27_0
- pyaudio=0.2.7=py27_0
- pycosat=0.6.1=py27_1
- pycparser=2.14=py27_1
- pycrypto=2.6.1=py27_4
- pycurl=7.43.0=py27_0
- pyflakes=1.3.0=py27_0
- pylint=1.5.4=py27_1
- pyparsing=2.1.4=py27_0
- pyqt=5.6.0=py27_0
- python.app=1.2=py27_4
- pyyaml=3.12=py27_0
- qt=5.6.0=0
- qtconsole=4.2.1=py27_1
- qtpy=1.1.2=py27_0
- readline=6.2=2
- redis=3.2.0=0
- rope=0.9.4=py27_1
- scikit-image=0.12.3=np111py27_1
- scikit-learn=0.17.1=np111py27_2
- scipy=0.18.1=np111py27_0
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- sockjs-tornado=1.0.3=py27_0
- spyder=3.0.0=py27_0
- sqlalchemy=1.0.13=py27_0
- ssl_match_hostname=3.4.0.2=py27_1
- statsmodels=0.6.1=np111py27_1
- tblib=1.3.0=py27_0
- tk=8.5.18=0
- unicodecsv=0.14.1=py27_0
- werkzeug=0.11.11=py27_0
- widgetsnbextension=1.2.6=py27_0
- wrapt=1.10.6=py27_0
- xlrd=1.0.0=py27_0
- xlsxwriter=0.9.3=py27_0
- xlwings=0.10.0=py27_0
- xlwt=1.1.2=py27_0
- pip:
  - alabaster==0.7.9
  - anaconda-client==1.5.1
  - babel==2.3.4
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - botocore==1.4.49
  - bottleneck==1.1.0
  - certifi==2016.8.31
  - click==6.6
  - cloudpickle==0.2.1
  - colorama==0.3.7
  - configparser==3.5.0
  - contextlib2==0.5.3
  - cycler==0.10.0
  - cytoolz==0.8.0
  - decorator==4.0.10
  - dill==0.2.5
  - distributed==1.13.2
  - dynd==0.7.3.dev1
  - enum34==1.1.6
  - et-xmlfile==1.0.1
  - filelock==2.0.6
  - flask==0.11.1
  - funcsigs==1.0.2
  - functools32==3.2.3.post2
  - futures==3.0.5
  - idna==2.1
  - imagesize==0.7.1
  - ipaddress==1.0.16
  - ipykernel==4.5.0
  - ipython==5.1.0
  - ipython-genutils==0.1.0
  - ipywidgets==5.2.2
  - itsdangerous==0.24
  - jinja2==2.8
  - jmespath==0.9.0
  - jsonschema==2.5.1
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - locket==0.2.0
  - lxml==3.6.4
  - msgpack-python==0.4.8
  - multipledispatch==0.4.8
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - nbconvert==4.2.0
  - nbformat==4.1.0
  - nbpresent==3.0.2
  - networkx==1.11
  - nltk==3.2.1
  - nose==1.3.7
  - notebook==4.2.3
  - numexpr==2.6.1
  - pandas==0.18.1
  - partd==0.3.6
  - path.py==8.2.1
  - pathlib2==2.1.0
  - patsy==0.4.1
  - pep8==1.7.0
  - pip==8.1.2
  - prompt-toolkit==1.0.3
  - ptyprocess==0.5.1
  - pyasn1==0.1.9
  - pygments==2.1.3
  - pyopenssl==16.0.0
  - pytest==2.9.2
  - python-dateutil==2.5.3
  - pytz==2016.6.1
  - pyzmq==15.4.0
  - qtawesome==0.3.3
  - requests==2.11.1
  - s3fs==0.0.7
  - s3transfer==0.1.8
  - singledispatch==3.4.0.3
  - six==1.10.0
  - snowballstemmer==1.2.1
  - sphinx==1.4.6
  - sympy==1.0
  - tables==3.2.3.1
  - terminado==0.6
  - toolz==0.8.0
  - tornado==4.4.1
  - traitlets==4.3.0
  - wcwidth==0.1.7
  - wheel==0.29.0
  - zict==0.0.3

